### ISSUE TITLE
No licence

### ISSUE THREAD

**Issue by Korne127** [kevinsqi/quicktime-event-trainer#33]
Hey,
I have found this project a while ago when I was searching for a way to train for quicktime events. I found it really great and useful.

I've had some ideas to contribute to the project and add onto the features (e.g. I needed to train for WASD quicktime events, not with a playstation controller). However, I've noticed that the project has no licence, which technically makes it illegal for me to contribute to the project and upload it, even if just for a pull request.

I'm really glad I found the project since it was the only project like that I could find at all. And I think other people are in the same situation and could benefit from it receiving additions like the ones I have imagined.

So I'd like to ask if you could add a licence and therefore enable other contributions and additions from the open source community.

**Comment by kevinsqi** [comment]
added the license!

**Comment by Korne127** [comment]
Thank you so much! I really appreciate it :D
